BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Dokument ADD
	CreateTime datetime NOT NULL CONSTRAINT DF_Dokument_CreateTime DEFAULT GetDate(),
	OwnerId nvarchar(128) NULL
GO
ALTER TABLE dbo.Dokument SET (LOCK_ESCALATION = TABLE)
GO
COMMIT



USE [ITech]
GO

/****** Object:  Table [dbo].[TestSettings]    Script Date: 2015-09-24 20:53:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TestSettings](
	[id] [int] NOT NULL,
	[Test_PeriodDay] [int] NOT NULL,
	[Test_BlokOnWalit] [int] NOT NULL,
 CONSTRAINT [PK_TestSettings] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TestSettings] ADD  CONSTRAINT [DF_Table_1_TestPeriodDay]  DEFAULT ((30)) FOR [Test_PeriodDay]
GO

ALTER TABLE [dbo].[TestSettings] ADD  CONSTRAINT [DF_TestSettings_Test_BlokOnWalit]  DEFAULT ((0)) FOR [Test_BlokOnWalit]
GO

