BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

ALTER TABLE dbo.InformationPlan
	DROP CONSTRAINT DF_InformationPlan_Enabled
GO
ALTER TABLE dbo.InformationPlan
	DROP COLUMN Enabled


ALTER TABLE dbo.InformationPlan ADD
	Enabled bit NOT NULL CONSTRAINT DF_InformationPlan_Enabled DEFAULT 1

	
GO
COMMIT
