BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
ALTER TABLE dbo.ItechUsers ADD	Deleted bit NOT NULL CONSTRAINT DF_ItechUsers_Deleted DEFAULT 0;
ALTER TABLE dbo.ItechUsers SET (LOCK_ESCALATION = TABLE);
update  dbo.ItechUsers set Deleted=1, [UserId]=UserId + 'Del' where [Enabled]=0;
COMMIT

update  dbo.[TestSettings] set [Test_Run]=0;
GO