/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ItechUsers SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Dokument SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.ItechUsersDokumentRead
	(
	DokId int NOT NULL,
	UserId int NOT NULL,
	FirsReadAt datetime NULL,
	LastReadAt datetime NULL,
	DokVersion int NOT NULL CONSTRAINT DF_ItechUsersDokumentRead_DokVersion DEFAULT 0
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ItechUsersDokumentRead ADD CONSTRAINT
	PK_ItechUsersDokumentRead PRIMARY KEY CLUSTERED
	(
	DokId,
	UserId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ItechUsersDokumentRead ADD CONSTRAINT
	FK_ItechUsersDokumentRead_Dokument FOREIGN KEY
	(
	DokId
	) REFERENCES dbo.Dokument
	(
	Id
	) ON UPDATE  NO ACTION
	 ON DELETE  NO ACTION

GO
ALTER TABLE dbo.ItechUsersDokumentRead ADD CONSTRAINT
	FK_ItechUsersDokumentRead_ItechUsers FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.ItechUsers
	(
	id
	) ON UPDATE  NO ACTION
	 ON DELETE  NO ACTION

GO
ALTER TABLE dbo.ItechUsersDokumentRead SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Dokument ADD
	Version int NOT NULL CONSTRAINT DF_Dokument_Version DEFAULT 0
GO
ALTER TABLE dbo.Dokument SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
