//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRoles
    {
        public AspNetRoles()
        {
            this.ItechUsersRoles = new HashSet<ItechUsersRoles>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ItechUsersRoles> ItechUsersRoles { get; set; }
    }
}
