//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationPlan
    {
        public InformationPlan()
        {
            this.Dokument = new HashSet<Dokument>();
            this.Resource = new HashSet<Resource>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime LastWriteTime { get; set; }
        public string WorkProcess { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<Dokument> Dokument { get; set; }
        public virtual ICollection<Resource> Resource { get; set; }
    }
}
