//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorie
    {
        public Kategorie()
        {
            this.Dokument = new HashSet<Dokument>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Dokument> Dokument { get; set; }
    }
}
