//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPriority
    {
        public NewsPriority()
        {
            this.News = new HashSet<News>();
            this.NewsItems1 = new HashSet<NewsItems>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string CssName { get; set; }
    
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<NewsItems> NewsItems1 { get; set; }
    }
}
