//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsItems
    {
        public NewsItems()
        {
            this.News = new HashSet<News>();
        }
    
        public int Id { get; set; }
        public string NewsText { get; set; }
        public Nullable<System.DateTime> ValidEnd { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public int NewsPriorityId { get; set; }
    
        public virtual ICollection<News> News { get; set; }
        public virtual NewsPriority NewsPriority1 { get; set; }
    }
}
