//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestKompetencji2
    {
        public int id { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> finishedAt { get; set; }
        public int UserId { get; set; }
        public string xml { get; set; }
        public Nullable<int> score { get; set; }
        public string accessionNumber { get; set; }
        public int stateId { get; set; }
    }
}
