//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstrukcjeProdukcyjne.ServiceDokument {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDokument.IServiceDokument")]
    public interface IServiceDokument {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDokument/DownloadFile", ReplyAction="http://tempuri.org/IServiceDokument/DownloadFileResponse")]
        System.IO.Stream DownloadFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDokument/DownloadFile", ReplyAction="http://tempuri.org/IServiceDokument/DownloadFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDokument/DownloadDokument", ReplyAction="http://tempuri.org/IServiceDokument/DownloadDokumentResponse")]
        System.IO.Stream DownloadDokument(int idd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDokument/DownloadDokument", ReplyAction="http://tempuri.org/IServiceDokument/DownloadDokumentResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadDokumentAsync(int idd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDokumentChannel : InstrukcjeProdukcyjne.ServiceDokument.IServiceDokument, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDokumentClient : System.ServiceModel.ClientBase<InstrukcjeProdukcyjne.ServiceDokument.IServiceDokument>, InstrukcjeProdukcyjne.ServiceDokument.IServiceDokument {
        
        public ServiceDokumentClient() {
        }
        
        public ServiceDokumentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDokumentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDokumentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDokumentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream DownloadFile() {
            return base.Channel.DownloadFile();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync() {
            return base.Channel.DownloadFileAsync();
        }
        
        public System.IO.Stream DownloadDokument(int idd) {
            return base.Channel.DownloadDokument(idd);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadDokumentAsync(int idd) {
            return base.Channel.DownloadDokumentAsync(idd);
        }
    }
}
