//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Areas.Testy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowedCategories
    {
        public int id { get; set; }
        public int resourceId { get; set; }
        public int categoryId { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
