//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Areas.Testy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorie
    {
        public Kategorie()
        {
            this.Pytania = new HashSet<Pytania>();
            this.AllowedCategories = new HashSet<AllowedCategories>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Pytania> Pytania { get; set; }
        public virtual ICollection<AllowedCategories> AllowedCategories { get; set; }
    }
}
