//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Areas.Testy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odpowiedzi
    {
        public int id { get; set; }
        public int questionId { get; set; }
        public string content { get; set; }
        public Nullable<int> order { get; set; }
        public bool is_correct { get; set; }
    
        public virtual Pytania Pytania { get; set; }
    }
}
