//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Areas.Testy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pytania
    {
        public Pytania()
        {
            this.Odpowiedzi = new HashSet<Odpowiedzi>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string content { get; set; }
        public int answer_type { get; set; }
        public int categoryId { get; set; }
        public string keywords { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
        public virtual ICollection<Odpowiedzi> Odpowiedzi { get; set; }
    }
}
