//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Areas.Testy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanTestu
    {
        public StanTestu()
        {
            this.TestKompetencji = new HashSet<TestKompetencji>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<TestKompetencji> TestKompetencji { get; set; }
    }
}
