//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Areas.Testy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestyEntities : DbContext
    {
        public TestyEntities()
            : base("name=TestyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pytania> Pytania { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Odpowiedzi> Odpowiedzi { get; set; }
        public virtual DbSet<RodzajOdpowiedzi> RodzajOdpowiedzi { get; set; }
        public virtual DbSet<TestKompetencji> TestKompetencji { get; set; }
        public virtual DbSet<TestKompetencjiLog> TestKompetencjiLog { get; set; }
        public virtual DbSet<AllowedCategories> AllowedCategories { get; set; }
        public virtual DbSet<StanTestu> StanTestu { get; set; }
    }
}
