//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechSite.Areas.Testy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestKompetencjiLog
    {
        public int id { get; set; }
        public int TestId { get; set; }
        public System.DateTime loggedAt { get; set; }
        public int questionId { get; set; }
        public string answers { get; set; }
    
        public virtual TestKompetencji TestKompetencji { get; set; }
    }
}
