//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechInstrukcjeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItechUsers
    {
        public ItechUsers()
        {
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public int id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string CardNo { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
