//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechInstrukcjeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.InformationPlanWorkstation = new HashSet<InformationPlan>();
            this.ModelsWorkstation = new HashSet<ModelsWorkstation>();
            this.ModelsWorkstationModel = new HashSet<ModelsWorkstation>();
            this.InformationPlanModel = new HashSet<InformationPlan>();
            this.Workstation = new HashSet<Workstation>();
            this.Resource1 = new HashSet<Resource>();
            this.Resource2 = new HashSet<Resource>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public System.DateTime LastWriteTime { get; set; }
        public string No { get; set; }
        public string WorkProcess { get; set; }
        public bool Enabled { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string Factory { get; set; }
    
        public virtual ICollection<InformationPlan> InformationPlanWorkstation { get; set; }
        public virtual News News { get; set; }
        public virtual ICollection<ModelsWorkstation> ModelsWorkstation { get; set; }
        public virtual ICollection<ModelsWorkstation> ModelsWorkstationModel { get; set; }
        public virtual ICollection<InformationPlan> InformationPlanModel { get; set; }
        public virtual ICollection<Workstation> Workstation { get; set; }
        public virtual ICollection<Resource> Resource1 { get; set; }
                [System.Runtime.Serialization.IgnoreDataMember]
        public virtual ICollection<Resource> Resource2 { get; set; }
    }
}
