//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechInstrukcjeModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class Workstation
    {
        public int Id { get; set; }
        public int idR { get; set; }
        public string WorkstationGroup { get; set; }
        public string Factory { get; set; }
        public string Area { get; set; }
        public string Sterownik_Ip { get; set; }
        public string Sterownik_Model { get; set; }
        public Nullable<int> Setrownik_DB { get; set; }

         [IgnoreDataMember]
        public virtual Resource Resource { get; set; }
    }
}
